### ISSUE TITLE
Add an option to generate a markdown report

### ISSUE THREAD

**Issue by devmil** [bmw-tech/dart_apitool#137]
**Is your feature request related to a problem? Please describe.**
In our CI pipeline we would like to have a detailed explanation why the version number is incorrect.

**Describe the solution you'd like**
Provide an option to generate a markdown based report and save it to a file.
This markdown report could then show the changes and already link to the wiki page explaining the details about the detected change.
Our CI could then use the content of that markdown file and post it as a comment to the pull request.

**Describe alternatives you've considered**
Currently we parse the output of dart_apitool to get the part of the detected changes.

**Comment by Leftwitch** [comment]
@devmil we might be able to close this issue aswell now :)
