### ISSUE TITLE
Renaming a file should not detect a breaking change

### ISSUE THREAD

**Issue by passsy** [bmw-tech/dart_apitool#167]
I moved interface `CreateMatchers` from file `a.dart` to `b.dart`. The tool detected a breaking change

```
BREAKING CHANGES
└── Interface "CreateMatchers" removed (CI01)
Non-Breaking changestilities 0.5.0 (0.8.0 available)
├── Interface "CreateMatchers" added (CI02) (minor)
```

Expected result:

no diff, the interface was moved, neither added nor deleted.

**Comment by devmil** [comment]
Thanks for your bug report! I created a PR to solve that issue. May take a bit for that to be merged due to Christmas Season
