### ISSUE TITLE
Flutter recognition not working for transitive dependencies

### ISSUE THREAD

**Issue by mosuem** [bmw-tech/dart_apitool#177]
**Describe the bug**
The apitool checks if a package should use `flutter ...` or `dart ...` commands by [checking the pubspec for `flutter`](https://github.com/bmw-tech/dart_apitool/blob/98480fbbef63a43dd67280b231eb6bbbbe60d444/lib/src/analyze/package_api_analyzer.dart#L349) - but this does not work if flutter is a transitive dependency, leading to failures such as [this](https://github.com/dart-lang/native/actions/runs/8064840467/job/22029510785?pr=973). There, the package `jnigen` depends on `jni` which depends on `flutter`.

At least that is my working assumption on what is going on there. Maybe instead of the `pubspec.yaml`, the `pubspec.lock` file should be checked using `package:pubspec_lock_parse`?

**Comment by devmil** [comment]
@mosuem do you know how to reproduce this issue?
I tried to check out the commit that failed the pipeline and ran `dart pub get` in the `pkgs/jnigen` directory but dart was happy 🤷‍♂️
I even tried to run `dart_apitool diff` on main vs f6b527a3d4bc38f5c36a0147a8d91e830f34783f and this worked as well.
Maybe this has something to do with where dart and flutter are located (like stand-alone dart sdk vs dart sdk from Flutter)?

looking into the pubspec.lock will be difficult without a `pub get` run 😉 so we would need another way of detecting or specifying that Flutter requirement.

**Comment by devmil** [comment]
even running `pub get` with a stand-alone dart sdk here on a Mac seems to work.
I will try to use docker and a Linux environment to reproduce this issue

**Comment by mosuem** [comment]
> looking into the pubspec.lock will be difficult without a pub get run

right.. @HosseinYousefi any idea why the jni/jnigen repo might complain about using `dart ...` commands?

**Comment by devmil** [comment]
@mosuem @HosseinYousefi  I tried to reproduce that issue with inside a Docker container but this worked as well: https://gist.github.com/devmil/5c4d66e7f5aea38c18a49ac108a3c030

I also checked the health GH runner setup and if I'm not mistaken then it installs the stand-alone dart only if flutter is disabled, right?

**Comment by mosuem** [comment]
> I tried to reproduce that issue inside a Docker container but this worked as well

Thanks! Weird error then.

> I also checked the health GH runner setup and if I'm not mistaken then it installs the stand-alone dart only if flutter is disabled, right?

Yes, it should only install Flutter in this case.

**Comment by devmil** [comment]
@mosuem we could make that flutter / dart decision configurable so that packages could override the decision dart_apitool would make
