### ISSUE TITLE
Respect `@visibleForTesting` annotation

### ISSUE THREAD

**Issue by mosuem** [bmw-tech/dart_apitool#179]
**Describe the bug**
When running `dart-apitool extract --input . --set-exit-on-missing-export` to detect API leaks, the `@visibleForTesting` annotation seems to not be respected. (Also it would be nice to show where the leak occurs, and not only the symbol, to quickly see where the leak occurs).

**To Reproduce**

- Checkout `package:grpc` at https://github.com/grpc/grpc-dart
- Run `dart-apitool extract --input . --set-exit-on-missing-export`
- The output contains `ServerHandler` (it also contains `$1.Duration`, which doesn't seem to be exported anywhere..)

**Actual and Expected behavior**
If a symbol is annotated `@visibleForTesting`, it should not be considered as an API leak.

**System info (please complete the following information):**
 - `Dart SDK version: 3.4.0-257.0.dev (dev) (Thu Mar 21 09:03:49 2024 -0700) on "linux_x64"`
 - `0.18.0`

**Comment by mosuem** [comment]
Regarding `$1.Duration` - maybe there is also an issue with top-level functions, such as `parseErrorDetailsFromAny` in this case? I think it is the only method exposing the Duration class, but it is not exported outside of `lib/src` AFAIK.

**Comment by devmil** [comment]
If I'm not mistaken then $1.Duration is exported via RetryInfo in error_details?
Entry point: https://github.com/grpc/grpc-dart/blob/b05fafe77cffca15f56ca9bd33c5a51f6d2a7170/lib/grpc.dart#L45
RetryInfo constructor usage: https://github.com/grpc/grpc-dart/blob/b05fafe77cffca15f56ca9bd33c5a51f6d2a7170/lib/src/generated/google/rpc/error_details.pb.dart#L33
