### ISSUE TITLE
Get latest version by default in `diff` command

### ISSUE THREAD

**Issue by mosuem** [bmw-tech/dart_apitool#188]
As the `version` argument in [`dart pub cache`](https://dart.dev/tools/pub/cmd/pub-cache) is optional, it would be nice to have this reflected in [the code](https://github.com/bmw-tech/dart_apitool/blob/04e6ec780b240b91fff52a99f96e3e20d768f33b/lib/src/tooling/pub_interaction.dart#L23). This would allow for getting the latest version by specifying only the package in the diff command, e.g. `diff --old pub://package_name`.

**Comment by devmil** [comment]
Good input!
We will add that functionality. 

Please keep in mind that this approach (from the user side) might break situations in which you want to release a Bugfix version of an older package

**Comment by mosuem** [comment]
> Please keep in mind that this approach (from the user side) might break situations in which you want to release a Bugfix version of an older package version

Good point. This should be fairly uncommon though (hopefully...).
